version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: go-api-service
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-db-service
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
